name: SaneEconomy
author: AppleDash
main: org.appledash.saneeconomy.SaneEconomy
version: 0.5.3
softdepends: [Vault]
commands:
  balance:
    aliases: [bal]
    description: Get the balance of yourself or another player.
    usage: /<command> [player name]
    permission: saneeconomy.balance
  ecoadmin:
    aliases: [eco]
    description: Administer the economy.
    usage: /<command> <give/take/set> <player name> <amount>
    permission: saneeconomy.ecoadmin
  pay:
    aliases: [transfer]
    description: Give some of your money to another player.
    usage: /<command> <player> <amount>
    permission: saneeconomy.pay
  saneeconomy:
    aliases: [saneeco]
    description: Various admin commands for SaneEconomy.
    usage: /command reload-database
    pernission: saneeconomy.admin
